# Generated by Django 4.2 on 2023-07-03 10:24

import ckeditor_uploader.fields
import content.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Home Appliances', 'Home Appliances'), ('Computer and Office', 'Computer and Office'), ('Home & Garden', 'Home & Garden'), ('Sports & Entertainment', 'Sports & Entertainment'), ('Education & Office Supplies', 'Education & Office Supplies'), ('Toys & Hobbies', 'Toys & Hobbies'), ('Security & Protection', 'Security & Protection'), ('Automobiles & Motorcycles', 'Automobiles & Motorcycles'), ('Lights & Lighting', 'Lights & Lighting'), ('Consumer Electronics', 'Consumer Electronics'), ('Beauty & Health', 'Beauty & Health'), ('Shoes', 'Shoes'), ('Luggage & Bags', 'Luggage & Bags'), ('Electronic Components & Supplies', 'Electronic Components & Supplies'), ('Tools', 'Tools'), (' Mother & Kids', ' Mother & Kids'), ('Furniture', 'Furniture'), ('Jewelry & Accessories', 'Jewelry & Accessories'), ('Watches', 'Watches'), ('Hair Extensions and Wigs', 'Hair Extensions and Wigs'), ('Virtual Goods', 'Virtual Goods'), ('Novelty and Special Use', 'Novelty and Special Use'), ('Weddings and Events', 'Weddings and Events'), ('Women’s Clothing', 'Women’s Clothing'), ('Men’s Clothing', 'Men’s Clothing'), ('Apparel Accessories', 'Apparel Accessories'), ('Underwear and Sleepwears', 'Underwear and Sleepwears'), ('Cellphones & Telecommunications', 'Cellphones & Telecommunications')], max_length=100)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_number', models.IntegerField(blank=True, help_text='ads country number group range', null=True)),
                ('name', models.CharField(blank=True, choices=[('United States', 'United States'), ('United Kingdom', 'United Kingdom'), ('Canada', 'Canada'), ('Australia', 'Australia'), ('New Zealand', 'New Zealand'), ('Sweden', 'Sweden'), ('Denmark', 'Denmark'), ('Iceland', 'Iceland'), ('Norway', 'Norway'), ('Finland', 'Finland'), ('The Netherlands', 'The Netherlands'), ('Ireland', 'Ireland'), ('Germany', 'Germany'), ('South Korea', 'South Korea'), ('Switzerland', 'Switzerland'), ('Belgium', 'Belgium'), ('Israel', 'Israel'), ('Italy', 'Italy'), ('France', 'France'), ('Spain', 'Spain'), ('Portugal', 'Portugal'), ('Austria', 'Austria'), ('Hungary', 'Hungary'), ('Poland', 'Poland'), ('Czech Republic', 'Czech Republic'), ('UAE', 'UAE'), ('South Africa', 'South Africa'), ('The Philippines', 'The Philippines'), ('Japan', 'Japan'), ('Singapore', 'Singapore'), ('Argentina', 'Argentina'), ('Mexico', 'Mexico')], default='United States', max_length=100, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('shopify_links', models.CharField(blank=True, help_text='A link that will take to a single the store', max_length=500, null=True)),
                ('shopify_price', models.DecimalField(blank=True, decimal_places=2, help_text='Product price from shopify', max_digits=10, null=True)),
                ('product_thumbnail', models.ImageField(blank=True, default='products/defaut_image_store_light_blue_bag.jpg', null=True, upload_to='thumbnails/')),
                ('store_logo', models.ImageField(blank=True, default='products/defaut_image_store.png', null=True, upload_to='image_store/')),
                ('aliexpress_order', models.IntegerField(default=0, help_text='Amount of aliexpress order generated')),
                ('aliexpress_price', models.DecimalField(blank=True, decimal_places=2, help_text='Product price from aliexpress', max_digits=10, null=True)),
                ('ads_type', models.CharField(blank=True, choices=[('video', 'Video'), ('photo', 'Photo'), ('both', 'Both')], default='Video', max_length=250, null=True)),
                ('media_type', models.CharField(blank=True, choices=[('faceBook', 'FaceBook'), ('instagram', 'Instagram'), ('Tiktok', 'Tiktok')], default='video', max_length=250, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male or Female', 'Male or Female'), ('male', 'Male'), ('female', 'Female')], default='Male or Female', max_length=250, null=True)),
                ('technology', models.CharField(blank=True, max_length=250, null=True)),
                ('language', models.CharField(blank=True, choices=[('english', 'English'), ('armenian', 'Armenian'), ('belarusian', 'Belarusian'), ('bengali', 'Bengali'), ('bosnia', 'Bosnia'), ('bulgarian', 'Bulgarian'), ('bumese', 'Bumese'), ('catalan', 'Catalan'), ('central Kurdish', 'Central Kurdish'), ('croatian', 'Croatian'), ('czech', 'Czech'), ('danish', 'Danish'), ('dutch', 'Dutch'), ('estonian', 'Estonian'), ('finnish', 'Finnish'), ('french', 'French'), ('georgian', 'Georgian'), ('german', 'German'), ('gujarati', 'Gujarati'), ('haitian', 'Haitian'), ('hebrew', 'Hebrew'), ('hindi', 'Hindi'), ('hungarian', 'Hungarian'), ('indonesian', 'Indonesian'), ('italian', 'Italian'), ('japanese', 'Japanese'), ('javanese', 'Javanese'), ('kannada', 'Kannada'), ('kazakh', 'Kazakh'), ('khmer', 'Khmer'), ('korean', 'Korean'), ('latvian', 'Latvian'), ('lithuanian', 'Lithuanian'), ('maithili', 'Maithili'), ('malay', 'Malay'), ('malayalam', 'Malayalam'), ('mandarin Chinese', 'Mandarin Chinese'), ('marathi', 'Marathi'), ('modern Greek', 'Modern Greek'), ('nepali', 'Nepali'), ('north Azerbaijani', 'North Azerbaijani'), ('northern Uzbek', 'Northern Uzbek'), ('norwegian bokmål', 'Norwegian bokmål'), ('norwegian Nynorsk', 'Norwegian Nynorsk'), ('oriya', 'Oriya'), ('persian', 'Persian'), ('polish', 'Polish'), ('portuguese', 'Portuguese'), ('romanian', 'Romanian'), ('russian', 'Russian'), ('Serbian', 'Serbian'), ('slovak', 'Slovak'), ('slovenian', 'Slovenian'), ('somali', 'Somali'), ('spanish', 'Spanish'), ('sudanese', 'Sudanese'), ('swahili', 'Swahili'), ('swedish', 'Swedish'), ('tagalog', 'Tagalog'), ('tajik', 'Tajik'), ('tamil', 'Tamil'), ('telugu', 'Telugu'), ('thai', 'Thai'), ('tibetan', 'Tibetan'), ('turkish', 'Turkish'), ('turkmen', 'Turkmen'), ('uighur', 'Uighur'), ('ukrainian', 'Ukrainian'), ('urdu', 'Urdu'), ('vietnamese', 'Vietnamese')], default='English', max_length=250, null=True)),
                ('button', models.CharField(blank=True, choices=[('buy now', 'Buy Now'), ('shop now', 'Shop Now'), ('learn more', 'Learn More'), ('sign up', 'Sign Up'), ('send message', 'Send Message'), ('book now', 'Book Now'), ('install now', 'Install Now'), ('get directions', 'Get Directions'), ('watch more', 'Watch More'), ('view', 'View'), ('apply now', 'Apply Now'), ('like this page', 'Like This Page'), ('download', 'Download'), ('get offer', 'Get Offer'), ('get tickets', 'Get Tickets'), ('play game', 'Play Game'), ('try it', 'Try It'), ('contact us', 'Contact Us'), ('send whatsapp message', 'Send Whatsapp Message'), ('get quote', 'Get Quote'), ('call now', 'Call Now'), ('donate now', 'Donate Now'), ('buy tickets', 'Buy Tickets'), ('listen now', 'Listen Now'), ('subscribe', 'Subscribe'), ('get show times', 'Get Show Times'), ('view event', 'View Event'), ('see menu', 'See Menu'), ('read', 'Read'), ('use app', 'Use App'), ('order now', 'Order Now'), ('request time', 'Request Time'), ('join', 'Join'), ('open link', 'Open Link'), ('start order', 'Start Order'), ('install app', 'Install App'), ('get your code', 'Get Your Code'), ('see more', 'See More'), ('play now', 'Play Now'), ('see details', 'See Details'), ('open camera', 'Open Camera'), ('sell now', 'Sell Now'), ('buy', 'Buy'), ('about this website', 'About This Website'), ('messsage', 'Messsage'), ('follow', 'Follow'), ('try it', 'Try it'), ('like page', 'Like Page'), ('donate', 'Donate'), ('watch video', 'Watch Video'), ('visit website', 'Visit Website'), ('register now', 'Register Now'), ('email now', 'Email Now'), ('use offer', 'Use Offer'), ('add to profil', 'Add To Profil'), ('turn on', 'Turn On'), ('invite friends', 'Invite Friends'), ('see more', 'see more'), ('visit instagram profile', 'Visit Instagram Profile'), ('go live', 'go live'), ('add to cart', 'Add To Cart'), ('vote now', 'Vote Now'), ('intrested', 'Intrested'), ('see all events', 'See All Events'), ('save', 'Save'), ('search', 'Search'), ('remind me', 'Remind Me'), ('watch yours', 'Watch Yours'), ('save offer', 'Save Offer'), ('get deal', 'Get Deal'), ('get reminded', 'Get Reminded'), ('book test drive', 'Book Test Drive'), ('call', 'Call')], default='Buy Now', max_length=250, null=True)),
                ('facebook_shares', models.IntegerField(blank=True, default=0, help_text='Amount of shares generated', null=True)),
                ('facebook_comment', models.IntegerField(default=0, help_text='Amount of comment generated')),
                ('facebook_views', models.IntegerField(default=0, help_text='Amount of views generated')),
                ('facebook_like', models.IntegerField(default=0, help_text='Amount of facebook like')),
                ('facebook_wow', models.IntegerField(default=0, help_text='Amount of facebook wow')),
                ('facebook_love', models.IntegerField(default=0, help_text='Amount of facebook love')),
                ('facebook_haha', models.IntegerField(default=0, help_text='Amount of facebook haha')),
                ('facebook_sad', models.IntegerField(default=0, help_text='Amount of facebook sad')),
                ('facebook_angry', models.IntegerField(default=0, help_text='Amount of facebook angry')),
                ('text_that_comes_with_ads', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('read_more_text_that_comes_with_ads', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('number_of_store_selling', models.IntegerField(blank=True, default=0, help_text='Amount of store selling the product')),
                ('number_of_suppliers_selling', models.IntegerField(default=0, help_text='Amount of suppliers selling the product')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('is_faceBook', models.BooleanField(default=False)),
                ('is_pinterest', models.BooleanField(default=False)),
                ('is_tiktok', models.BooleanField(default=False)),
                ('has_video', models.BooleanField(default=False)),
                ('has_photo', models.BooleanField(default=False)),
                ('price_margin', models.DecimalField(decimal_places=2, default=0, help_text='Profit you get from this product', max_digits=10)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('aliexpress_total_sale', models.DecimalField(decimal_places=2, default=0, help_text='Amount of aliexpress sale generated', max_digits=10)),
                ('status', models.IntegerField(choices=[(0, 'Regular'), (1, 'Manager'), (2, 'Admin')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OtherAliexpressSuppliersLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, help_text='A link that will take to a single the Other Aliexpress Suppliers Links', max_length=500, null=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Other Aliexpress Suppliers Links',
            },
        ),
        migrations.CreateModel(
            name='OtherShopifyLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, help_text='A link that will take to a single the Other Shopify Links', max_length=500, null=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Other Shopify Links',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('stripe_price_id', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('shopify', 'Shopify'), ('wooCommerce', 'WooCommerce'), ('cart functionality', 'Cart Functionality'), ('magento', 'magento'), ('salesforce commerce cloud', 'Salesforce Commerce Cloud'), ('prestashop', 'PrestaShop'), ('vtex', 'VTEX'), ('bigcommerce', 'Bigcommerce'), ('ibm websphere commerce', 'IBM Websphere Commerce'), ('sap commerce cloud', 'SAP Commerce Cloud'), ('shopware', 'Shopware'), ('shoptet', 'Shoptet'), ('opencart', 'OpenCart'), ('nopcommerce', 'nopcommerce'), ('oracle commerce', 'Oracle Commerce'), ('intershop', 'Intershop'), ('hybris', 'Hybris'), ('zen cart', 'Zen Cart'), ('oracle commerce cloud', 'Oracle Commerce Cloud'), ('lightspeed ecom', 'Lightspeed eCom'), ('epages', 'EPages'), ('cloudcart', 'CloudCart'), ('kajabi', 'Kajabi'), ('loja integrada', 'Loja Integrada'), ('oxid eshop', 'OXID eShop'), ('riskified', 'Riskified'), ('x-cart', 'X-Cart'), ('commerce server', 'Commerce Server'), ('drupal commerce', 'Drupal Commerce'), ('oscommerce', 'osCommerce'), ('91app', '91App'), ('nuvemshop', 'Nuvemshop'), ('mycashflow', 'Mycashflow'), ('ticimax', 'Ticimax'), ('ecwid', 'Ecwid'), ('gambio', 'Gambio'), ('craft commerce', 'Craft Commerce'), ('ideasoft', 'Ideasoft'), ('ceres', 'Ceres'), ('t-soft', 'T-Soft'), ('storeden', 'Storeden'), ('vtex integrated store', 'VTEX Integrated Store'), ('ccv shop', 'CCV Shop'), ('big cartel', 'Big Cartel'), ('miva', 'Miva'), ('irroba', 'Irroba'), ('volusion', 'Volusion'), ('yepcomm', 'Yepcomm'), ('xtcommerce', 'xtCommerce'), ('ec-cube', 'EC-CUBE')], default='shopify', max_length=100)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vimeo_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='content.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stripe_subscription_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100)),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='content.pricing')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('ordered_date', models.DateTimeField(blank=True, null=True)),
                ('ordered', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(blank=True, help_text='ads like range', null=True)),
                ('name', models.CharField(blank=True, choices=[('Jan', 'Jan'), ('Feb', 'Feb'), ('Mar', 'Mar'), ('Apr', 'Apr'), ('May', 'May'), ('Jun', 'Jun')], default='Jan', max_length=100, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.course')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_number', models.IntegerField(blank=True, help_text='ads gender number group range', null=True)),
                ('name', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Unkwon', 'Unknown')], default='Female', max_length=100, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genders', to='content.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='OtherAliexpressSuppliersLinks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='OtherAliexpressSuppliersLinks', to='content.otheraliexpresssupplierslinks'),
        ),
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.category'),
        ),
        migrations.AddField(
            model_name='course',
            name='countries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.country'),
        ),
        migrations.AddField(
            model_name='course',
            name='name_of_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_name', to='content.store'),
        ),
        migrations.AddField(
            model_name='course',
            name='otherShopifyLinks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='other_shopify_links', to='content.othershopifylinks'),
        ),
        migrations.AddField(
            model_name='course',
            name='pricing_tiers',
            field=models.ManyToManyField(blank=True, to='content.pricing'),
        ),
        migrations.CreateModel(
            name='AliexpressOrderGrowth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.PositiveIntegerField(null=True)),
                ('name', models.CharField(blank=True, choices=[('Jan', 'Jan'), ('Feb', 'Feb'), ('Mar', 'Mar'), ('Apr', 'Apr'), ('May', 'May'), ('Jun', 'Jun')], max_length=100, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.course')),
            ],
        ),
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, help_text='ads age group range', null=True)),
                ('name', models.CharField(blank=True, choices=[('13-17', '13-17'), ('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-54', '45-54'), ('55-64', '55-64'), ('65+', '65+')], default='25-34', max_length=100, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.course')),
            ],
        ),
    ]
