# Generated by Django 4.2 on 2023-09-07 06:06

import ckeditor_uploader.fields
import content.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Home Appliances', 'Home Appliances'), ('Computer and Office', 'Computer and Office'), ('Home & Garden', 'Home & Garden'), ('Sports & Entertainment', 'Sports & Entertainment'), ('Education & Office Supplies', 'Education & Office Supplies'), ('Toys & Hobbies', 'Toys & Hobbies'), ('Security & Protection', 'Security & Protection'), ('Automobiles & Motorcycles', 'Automobiles & Motorcycles'), ('Lights & Lighting', 'Lights & Lighting'), ('Consumer Electronics', 'Consumer Electronics'), ('Beauty & Health', 'Beauty & Health'), ('Shoes', 'Shoes'), ('Luggage & Bags', 'Luggage & Bags'), ('Electronic Components & Supplies', 'Electronic Components & Supplies'), ('Tools', 'Tools'), (' Mother & Kids', ' Mother & Kids'), ('Furniture', 'Furniture'), ('Jewelry & Accessories', 'Jewelry & Accessories'), ('Watches', 'Watches'), ('Hair Extensions and Wigs', 'Hair Extensions and Wigs'), ('Virtual Goods', 'Virtual Goods'), ('Novelty and Special Use', 'Novelty and Special Use'), ('Weddings and Events', 'Weddings and Events'), ('Women’s Clothing', 'Women’s Clothing'), ('Men’s Clothing', 'Men’s Clothing'), ('Apparel Accessories', 'Apparel Accessories'), ('Underwear and Sleepwears', 'Underwear and Sleepwears'), ('Cellphones & Telecommunications', 'Cellphones & Telecommunications')], default='Beauty & Health', max_length=100)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('United States', 'United States'), ('United Kingdom', 'United Kingdom'), ('Canada', 'Canada'), ('Australia', 'Australia'), ('New Zealand', 'New Zealand'), ('Sweden', 'Sweden'), ('Denmark', 'Denmark'), ('Iceland', 'Iceland'), ('Norway', 'Norway'), ('Finland', 'Finland'), ('The Netherlands', 'The Netherlands'), ('Ireland', 'Ireland'), ('Germany', 'Germany'), ('South Korea', 'South Korea'), ('Switzerland', 'Switzerland'), ('Belgium', 'Belgium'), ('Israel', 'Israel'), ('Italy', 'Italy'), ('France', 'France'), ('Spain', 'Spain'), ('Portugal', 'Portugal'), ('Austria', 'Austria'), ('Hungary', 'Hungary'), ('Poland', 'Poland'), ('Czech Republic', 'Czech Republic'), ('UAE', 'UAE'), ('South Africa', 'South Africa'), ('The Philippines', 'The Philippines'), ('Japan', 'Japan'), ('Singapore', 'Singapore'), ('Argentina', 'Argentina'), ('Mexico', 'Mexico')], default='United States', max_length=100, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_product', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('shopify_price', models.DecimalField(decimal_places=2, help_text='Product price from shopify', max_digits=10)),
                ('aliexpress_price', models.DecimalField(blank=True, decimal_places=2, help_text='Product price from aliexpress', max_digits=10, null=True)),
                ('shopify_links', models.CharField(blank=True, help_text='A link that will take to a single the store', max_length=500, null=True)),
                ('product_thumbnail', models.ImageField(default='products/defaut_image_store_light_blue_bag.jpg', upload_to='thumbnails/')),
                ('store_logo', models.ImageField(blank=True, default='products/defaut_image_store.png', upload_to='image_store/')),
                ('aliexpress_order', models.IntegerField(default=0, help_text='Amount of aliexpress order generated')),
                ('countries', models.CharField(blank=True, choices=[('United States', 'United States'), ('United Kingdom', 'United Kingdom'), ('Canada', 'Canada'), ('Australia', 'Australia'), ('New Zealand', 'New Zealand'), ('Sweden', 'Sweden'), ('Denmark', 'Denmark'), ('Iceland', 'Iceland'), ('Norway', 'Norway'), ('Finland', 'Finland'), ('The Netherlands', 'The Netherlands'), ('Ireland', 'Ireland'), ('Germany', 'Germany'), ('South Korea', 'South Korea'), ('Switzerland', 'Switzerland'), ('Belgium', 'Belgium'), ('Israel', 'Israel'), ('Italy', 'Italy'), ('France', 'France'), ('Spain', 'Spain'), ('Portugal', 'Portugal'), ('Austria', 'Austria'), ('Hungary', 'Hungary'), ('Poland', 'Poland'), ('Czech Republic', 'Czech Republic'), ('UAE', 'UAE'), ('South Africa', 'South Africa'), ('The Philippines', 'The Philippines'), ('Japan', 'Japan'), ('Singapore', 'Singapore'), ('Argentina', 'Argentina'), ('Mexico', 'Mexico')], default='United States', max_length=250, null=True)),
                ('ship_from', models.CharField(blank=True, choices=[('Afghanistan', 'Afghanistan'), ('Aland Islands', 'Aland Islands'), ('Albania', 'Albania'), ('Aldemey', 'Aldemey'), ('Algeria', 'Algeria'), ('American Samoa', 'American Samoa'), ('Andorra', 'Andorra'), ('Angola', 'Angola'), ('Anguilla', 'Anguilla'), ('Antigua and Barbuda', 'Antigua and Barbuda'), ('Argentina', 'Argentina'), ('Armemia', 'Armemia'), ('Aruba', 'Aruba'), ('Ascension Island', 'Ascension Island'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('Azerbaijan', 'Azerbaijan'), ('Bahamas', 'Bahamas'), ('Bahrain', 'Bahrain'), ('Bangladesh', 'Bangladesh'), ('Barbados', 'Barbados'), ('Belarus', 'Belarus'), ('Belgium', 'Belgium'), ('Belize', 'Belize'), ('Benin', 'Benin'), ('Bermuda', 'Bermuda'), ('Bhutan', 'Bhutan'), ('Bolivia', 'Bolivia'), ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'), ('Botswana', 'Botswana'), ('Brazil', 'Brazil'), ('Virgin Islands(British)', 'Virgin Islands(British)'), ('Brunei', 'Brunei'), ('Bulgaria', 'Bulgaria'), ('Burkina Faso', 'Burkina Faso'), ('Burundi', 'Burundi'), ('Cambodia', 'Cambodia'), ('Cameroon', 'Cameroon'), ('Canada', 'Canada'), ('Cap Verte', 'Cap Verte'), ('Caribbean Netherlands', 'Caribbean Netherlands'), ('Cayman Islands', 'Cayman Islands'), ('Cental African Republic', 'Cental African Republic'), ('Chad', 'Chad'), ('Chile', 'Chile'), ('Christmas Island', 'Christmas Island'), ('Cocos (Keeling) Islands', 'Cocos (Keeling) Islands'), ('Colombia', 'Colombia'), ('Comoros', 'Comoros'), ('Congo, Democratic Republic of the', 'Congo, Democratic Republic of the'), ('Costa Rica', 'Costa Rica'), ('Côte d’Ivoire', 'Côte d’Ivoire'), ('Croatia', 'Croatia'), ('Curacao', 'Curacao'), ('Cyprus', 'Cyprus'), ('Czech Republic', 'Czech Republic'), ('Denmark', 'Denmark'), ('Djibouti', 'Djibouti'), ('Dominica Dominican Republic', 'Dominica Dominican Republic'), ('East Timor (Timor-Leste)', 'East Timor (Timor-Leste)'), ('Ecuador', 'Ecuador'), ('Egypt', 'Egypt'), ('El Salvador', 'El Salvador'), ('Equatorial Guinea', 'Equatorial Guinea'), ('Eritrea', 'Eritrea'), ('Estonia', 'Estonia'), ('Ethiopia', 'Ethiopia'), ('Falkand Islands(Malvinas)', 'Falkand Islands(Malvinas)'), ('Faroe Islands', 'Faroe Islands'), ('Fiji', 'Fiji'), ('Finland', 'Finland'), ('France', 'France'), ('Gabon', 'Gabon'), ('The Gambia', 'The Gambia'), ('Georgia', 'Georgia'), ('Germany', 'Germany'), ('Gibraltar', 'Gibraltar'), ('Greece', 'Greece'), ('Grenada', 'Grenada'), ('Guan', 'Guan'), ('Guatemala', 'Guatemala'), ('Guernsey', 'Guernsey'), ('Guinea', 'Guinea'), ('Guinea-Bissau', 'Guinea-Bissau'), ('Guyana', 'Guyana'), ('French Guyana', 'French Guyana'), ('Haiti', 'Haiti'), ('Honduras', 'Honduras'), ('Hungary', 'Hungary'), ('Hong Kong, China', 'Hong Kong, China'), ('Iceland', 'Iceland'), ('India', 'India'), ('Indonesia', 'Indonesia'), ('Iraq', 'Iraq'), ('Ireland', 'Ireland'), ('Israel', 'Israel'), ('Italy', 'Italy'), ('Jamaica', 'Jamaica'), ('Japan', 'Japan'), ('Jersey', 'Jersey'), ('Jordan', 'Jordan'), ('Kazakhstan', 'Kazakhstan'), ('Kenya', 'Kenya'), ('Kiribati', 'Kiribati'), ('Korea', 'Korea'), ('Kosovo', 'Kosovo'), ('Kuwait', 'Kuwait'), ('Kyrgyzstan', 'Kyrgyzstan'), ("Laos People's Democratic Republic", "Laos People's Democratic Republic"), ('Latvia', 'Latvia'), ('Lebanon', 'Lebanon'), ('Lesotho', 'Lesotho'), ('Liberia', 'Liberia'), ('Libya', 'Libya'), ('Liechtenstein', 'Liechtenstein'), ('Lithuania', 'Lithuania'), ('Luxembourg', 'Luxembourg'), ('Macao(China)', 'Macao(China)'), ('Madagascar', 'Madagascar'), ('Malawi', 'Malawi'), ('Malaysia', 'Malaysia'), ('Maldives', 'Maldives'), ('Mali', 'Mali'), ('Malta', 'Malta'), ('Marshall Islands', 'Marshall Islands'), ('Martinique', 'Martinique'), ('Mauritania', 'Mauritania'), ('Mauritius', 'Mauritius'), ('Mayotte', 'Mayotte'), ('Mexico', 'Mexico'), ('Micronesia', 'Micronesia'), ('Monaco', 'Monaco'), ('Mongolia', 'Mongolia'), ('Montenegro', 'Montenegro'), ('Montserrat', 'Montserrat'), ('Morocco', 'Morocco'), ('Mozambique', 'Mozambique'), ('Myanmar (Burma)', 'Myanmar (Burma)'), ('Namibia', 'Namibia'), ('Nauru', 'Nauru'), ('Nepal', 'Nepal'), ('Netherlands', 'Netherlands'), ('Netherlands Antilles', 'Netherlands Antilles'), ('New Caledonia', 'New Caledonia'), ('New Zealand', 'New Zealand'), ('Nicaragua', 'Nicaragua'), ('Niger', 'Niger'), ('Nigeria', 'Nigeria'), ('Niue', 'Niue'), ('Norfolk Islands', 'Norfolk Islands'), ('North Macedonia', 'North Macedonia'), ('Norway', 'Norway'), ('Oman', 'Oman'), ('Other Country', 'Other Country'), ('Pakistan', 'Pakistan'), ('Palau', 'Palau'), ('Panama', 'Panama'), ('Papua New Guinea', 'Papua New Guinea'), ('Paraguay', 'Paraguay'), ('Peru', 'Peru'), ('Philippines', 'Philippines'), ('Poland', 'Poland'), ('Portugal', 'Portugal'), ('Qatar', 'Qatar'), ('Moldova', 'Moldova'), ('Romania', 'Romania'), ('Russia Federation', 'Russia Federation'), ('Rwanda', 'Rwanda'), ('Saint Barthelemy', 'Saint Barthelemy'), ('Saint Kitts and Nevis', 'Saint Kitts and Nevis'), ('Saint Lucia', 'Saint Lucia'), ('Saint Martin', 'Saint Martin'), ('St Pierre and Miquelon', 'St Pierre and Miquelon'), ('Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines'), ('Samoa', 'Samoa'), ('San Marino', 'San Marino'), ('Sao Tome and Principe', 'Sao Tome and Principe'), ('Saudi Arabia', 'Saudi Arabia'), ('Senegal', 'Senegal'), ('Serbia', 'Serbia'), ('Seychelles', 'Seychelles'), ('Sierra Leone', 'Sierra Leone'), ('Singapore', 'Singapore'), ('Sint Maarten', 'Sint Maarten'), ('Slovakia', 'Slovakia'), ('Slovenia', 'Slovenia'), ('Solomon Islands', 'Solomon Islands'), ('Somalia', 'Somalia'), ('South Africa', 'South Africa'), ('Spain', 'Spain'), ('Sri Lanka', 'Sri Lanka'), ('Sudan', 'Sudan'), ('Sudan, South', 'Sudan, South'), ('Suriname', 'Suriname'), ('Swaziland', 'Swaziland'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Taiwan, China', 'Taiwan, China'), ('Tajikistan', 'Tajikistan'), ('Tanzania', 'Tanzania'), ('Thailand', 'Thailand'), ('Togo', 'Togo'), ('Tonga', 'Tonga'), ('Trinidad and Tobago', 'Trinidad and Tobago'), ('Tunisia', 'Tunisia'), ('Turkey', 'Turkey'), ('Turkmenistan', 'Turkmenistan'), ('Tuvalu', 'Tuvalu'), ('Uganda', 'Uganda'), ('Ukraine', 'Ukraine'), ('United Arab Emirates', 'United Arab Emirates'), ('United Kingdom', 'United Kingdom'), ('United States', 'United States'), ('Uruguay', 'Uruguay'), ('Uzbekistan', 'Uzbekistan'), ('Vanuatu', 'Vanuatu'), ('Vatican City', 'Vatican City'), ('Venezuela', 'Venezuela'), ('Vietnam', 'Vietnam'), ('Yemen', 'Yemen'), ('Zambia', 'Zambia'), ('Zimbabwe', 'Zimbabwe'), ('Mainland, China', 'Mainland, China')], default='Hong Kong, China', max_length=250, null=True)),
                ('ads_type', models.CharField(blank=True, choices=[('video', 'Video'), ('photo', 'Photo'), ('both', 'Both')], default='video', max_length=250, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male or Female', 'Male or Female'), ('male', 'Male'), ('female', 'Female')], default='male or Female', max_length=250, null=True)),
                ('technology', models.CharField(blank=True, choices=[('shopify', 'Shopify'), ('wooCommerce', 'WooCommerce'), ('cart functionality', 'Cart Functionality'), ('magento', 'magento'), ('salesforce commerce cloud', 'Salesforce Commerce Cloud'), ('prestashop', 'PrestaShop'), ('vtex', 'VTEX'), ('bigcommerce', 'Bigcommerce'), ('ibm websphere commerce', 'IBM Websphere Commerce'), ('sap commerce cloud', 'SAP Commerce Cloud'), ('shopware', 'Shopware'), ('shoptet', 'Shoptet'), ('opencart', 'OpenCart'), ('nopcommerce', 'nopcommerce'), ('oracle commerce', 'Oracle Commerce'), ('intershop', 'Intershop'), ('hybris', 'Hybris'), ('zen cart', 'Zen Cart'), ('oracle commerce cloud', 'Oracle Commerce Cloud'), ('lightspeed ecom', 'Lightspeed eCom'), ('epages', 'EPages'), ('cloudcart', 'CloudCart'), ('kajabi', 'Kajabi'), ('loja integrada', 'Loja Integrada'), ('oxid eshop', 'OXID eShop'), ('riskified', 'Riskified'), ('x-cart', 'X-Cart'), ('commerce server', 'Commerce Server'), ('drupal commerce', 'Drupal Commerce'), ('oscommerce', 'osCommerce'), ('91app', '91App'), ('nuvemshop', 'Nuvemshop'), ('mycashflow', 'Mycashflow'), ('ticimax', 'Ticimax'), ('ecwid', 'Ecwid'), ('gambio', 'Gambio'), ('craft commerce', 'Craft Commerce'), ('ideasoft', 'Ideasoft'), ('ceres', 'Ceres'), ('t-soft', 'T-Soft'), ('storeden', 'Storeden'), ('vtex integrated store', 'VTEX Integrated Store'), ('ccv shop', 'CCV Shop'), ('big cartel', 'Big Cartel'), ('miva', 'Miva'), ('irroba', 'Irroba'), ('volusion', 'Volusion'), ('yepcomm', 'Yepcomm'), ('xtcommerce', 'xtCommerce'), ('ec-cube', 'EC-CUBE')], default='shopify', max_length=250, null=True)),
                ('language', models.CharField(blank=True, choices=[('english', 'English'), ('armenian', 'Armenian'), ('belarusian', 'Belarusian'), ('bengali', 'Bengali'), ('bosnia', 'Bosnia'), ('bulgarian', 'Bulgarian'), ('bumese', 'Bumese'), ('catalan', 'Catalan'), ('central Kurdish', 'Central Kurdish'), ('croatian', 'Croatian'), ('czech', 'Czech'), ('danish', 'Danish'), ('dutch', 'Dutch'), ('estonian', 'Estonian'), ('finnish', 'Finnish'), ('french', 'French'), ('georgian', 'Georgian'), ('german', 'German'), ('gujarati', 'Gujarati'), ('haitian', 'Haitian'), ('hebrew', 'Hebrew'), ('hindi', 'Hindi'), ('hungarian', 'Hungarian'), ('indonesian', 'Indonesian'), ('italian', 'Italian'), ('japanese', 'Japanese'), ('javanese', 'Javanese'), ('kannada', 'Kannada'), ('kazakh', 'Kazakh'), ('khmer', 'Khmer'), ('korean', 'Korean'), ('latvian', 'Latvian'), ('lithuanian', 'Lithuanian'), ('maithili', 'Maithili'), ('malay', 'Malay'), ('malayalam', 'Malayalam'), ('mandarin Chinese', 'Mandarin Chinese'), ('marathi', 'Marathi'), ('modern Greek', 'Modern Greek'), ('nepali', 'Nepali'), ('north Azerbaijani', 'North Azerbaijani'), ('northern Uzbek', 'Northern Uzbek'), ('norwegian bokmål', 'Norwegian bokmål'), ('norwegian Nynorsk', 'Norwegian Nynorsk'), ('oriya', 'Oriya'), ('persian', 'Persian'), ('polish', 'Polish'), ('portuguese', 'Portuguese'), ('romanian', 'Romanian'), ('russian', 'Russian'), ('Serbian', 'Serbian'), ('slovak', 'Slovak'), ('slovenian', 'Slovenian'), ('somali', 'Somali'), ('spanish', 'Spanish'), ('sudanese', 'Sudanese'), ('swahili', 'Swahili'), ('swedish', 'Swedish'), ('tagalog', 'Tagalog'), ('tajik', 'Tajik'), ('tamil', 'Tamil'), ('telugu', 'Telugu'), ('thai', 'Thai'), ('tibetan', 'Tibetan'), ('turkish', 'Turkish'), ('turkmen', 'Turkmen'), ('uighur', 'Uighur'), ('ukrainian', 'Ukrainian'), ('urdu', 'Urdu'), ('vietnamese', 'Vietnamese')], default='english', max_length=250, null=True)),
                ('button', models.CharField(blank=True, choices=[('buy now', 'Buy Now'), ('shop now', 'Shop Now'), ('learn more', 'Learn More'), ('sign up', 'Sign Up'), ('send message', 'Send Message'), ('book now', 'Book Now'), ('install now', 'Install Now'), ('get directions', 'Get Directions'), ('watch more', 'Watch More'), ('view', 'View'), ('apply now', 'Apply Now'), ('like this page', 'Like This Page'), ('download', 'Download'), ('get offer', 'Get Offer'), ('get tickets', 'Get Tickets'), ('play game', 'Play Game'), ('try it', 'Try It'), ('contact us', 'Contact Us'), ('send whatsapp message', 'Send Whatsapp Message'), ('get quote', 'Get Quote'), ('call now', 'Call Now'), ('donate now', 'Donate Now'), ('buy tickets', 'Buy Tickets'), ('listen now', 'Listen Now'), ('subscribe', 'Subscribe'), ('get show times', 'Get Show Times'), ('view event', 'View Event'), ('see menu', 'See Menu'), ('read', 'Read'), ('use app', 'Use App'), ('order now', 'Order Now'), ('request time', 'Request Time'), ('join', 'Join'), ('open link', 'Open Link'), ('start order', 'Start Order'), ('install app', 'Install App'), ('get your code', 'Get Your Code'), ('see more', 'See More'), ('play now', 'Play Now'), ('see details', 'See Details'), ('open camera', 'Open Camera'), ('sell now', 'Sell Now'), ('buy', 'Buy'), ('about this website', 'About This Website'), ('messsage', 'Messsage'), ('follow', 'Follow'), ('try it', 'Try it'), ('like page', 'Like Page'), ('donate', 'Donate'), ('watch video', 'Watch Video'), ('visit website', 'Visit Website'), ('register now', 'Register Now'), ('email now', 'Email Now'), ('use offer', 'Use Offer'), ('add to profil', 'Add To Profil'), ('turn on', 'Turn On'), ('invite friends', 'Invite Friends'), ('see more', 'see more'), ('visit instagram profile', 'Visit Instagram Profile'), ('go live', 'go live'), ('add to cart', 'Add To Cart'), ('vote now', 'Vote Now'), ('intrested', 'Intrested'), ('see all events', 'See All Events'), ('save', 'Save'), ('search', 'Search'), ('remind me', 'Remind Me'), ('watch yours', 'Watch Yours'), ('save offer', 'Save Offer'), ('get deal', 'Get Deal'), ('get reminded', 'Get Reminded'), ('book test drive', 'Book Test Drive'), ('call', 'Call')], default='buy now', max_length=250, null=True)),
                ('facebook_shares', models.IntegerField(blank=True, default=0, help_text='Amount of shares generated', null=True)),
                ('facebook_comment', models.IntegerField(default=0, help_text='Amount of comment generated')),
                ('facebook_views', models.IntegerField(default=0, help_text='Amount of views generated')),
                ('facebook_like', models.IntegerField(default=0, help_text='Amount of facebook like')),
                ('facebook_wow', models.IntegerField(default=0, help_text='Amount of facebook wow')),
                ('facebook_love', models.IntegerField(default=0, help_text='Amount of facebook love')),
                ('facebook_haha', models.IntegerField(default=0, help_text='Amount of facebook haha')),
                ('facebook_sad', models.IntegerField(default=0, help_text='Amount of facebook sad')),
                ('facebook_angry', models.IntegerField(default=0, help_text='Amount of facebook angry')),
                ('text_that_comes_with_ads', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('read_more_text_that_comes_with_ads', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('number_of_store_selling', models.IntegerField(blank=True, default=0, help_text='Amount of store selling the product')),
                ('number_of_suppliers_selling', models.IntegerField(default=0, help_text='Amount of suppliers selling the product')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('is_faceBook', models.BooleanField(default=False)),
                ('is_pinterest', models.BooleanField(default=False)),
                ('is_tiktok', models.BooleanField(default=False)),
                ('has_video', models.BooleanField(default=False)),
                ('has_photo', models.BooleanField(default=False)),
                ('price_margin', models.DecimalField(decimal_places=2, default=0, help_text='Profit you get from this product', max_digits=10)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('aliexpress_total_sale', models.DecimalField(decimal_places=2, default=0, help_text='Amount of aliexpress sale generated', max_digits=10)),
                ('site_type', models.IntegerField(choices=[(0, 'facebook'), (1, 'instagram'), (2, 'pinterest')], default=0)),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.category')),
                ('first_related_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_related', to='content.course')),
            ],
            options={
                'verbose_name_plural': '1. Courses',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('stripe_price_id', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': '1. Stores',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vimeo_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='content.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stripe_subscription_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100)),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='content.pricing')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OtherShopifyLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, help_text='A link that will take to a single the Other Shopify Links', max_length=500, null=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.course')),
            ],
            options={
                'verbose_name_plural': 'Other Shopify Links',
            },
        ),
        migrations.CreateModel(
            name='OtherAliexpressSuppliersLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, help_text='A link that will take to a single the Other Aliexpress Suppliers Links', max_length=500, null=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.course')),
            ],
            options={
                'verbose_name_plural': 'Other Aliexpress Suppliers Links',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('ordered_date', models.DateTimeField(blank=True, null=True)),
                ('ordered', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(blank=True, help_text='ads like range', null=True)),
                ('name', models.CharField(blank=True, choices=[('Jan', 'Jan'), ('Feb', 'Feb'), ('Mar', 'Mar'), ('Apr', 'Apr'), ('May', 'May'), ('Jun', 'Jun')], default='Jan', max_length=100, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.course')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_number', models.IntegerField(blank=True, help_text='ads gender number group range', null=True)),
                ('name', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Unkwon', 'Unknown')], default='Female', max_length=100, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genders', to='content.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='name_of_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_name', to='content.store'),
        ),
        migrations.AddField(
            model_name='course',
            name='pricing_tiers',
            field=models.ManyToManyField(blank=True, to='content.pricing'),
        ),
        migrations.AddField(
            model_name='course',
            name='second_related_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_related', to='content.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='third_related_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_related', to='content.course'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('population', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.course')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='AliexpressOrderGrowth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.PositiveIntegerField(null=True)),
                ('name', models.CharField(blank=True, choices=[('Jan', 'Jan'), ('Feb', 'Feb'), ('Mar', 'Mar'), ('Apr', 'Apr'), ('May', 'May'), ('Jun', 'Jun')], max_length=100, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.course')),
            ],
        ),
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, help_text='ads age group range', null=True)),
                ('name', models.CharField(blank=True, choices=[('13-17', '13-17'), ('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-54', '45-54'), ('55-64', '55-64'), ('65+', '65+')], default='25-34', max_length=100, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.course')),
            ],
        ),
    ]
