# Generated by Django 4.2 on 2023-09-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(blank=True, choices=[('Home Appliances', 'Home Appliances'), ('Computer and Office', 'Computer and Office'), ('Home & Garden', 'Home & Garden'), ('Sports & Entertainment', 'Sports & Entertainment'), ('Education & Office Supplies', 'Education & Office Supplies'), ('Toys & Hobbies', 'Toys & Hobbies'), ('Security & Protection', 'Security & Protection'), ('Automobiles & Motorcycles', 'Automobiles & Motorcycles'), ('Lights & Lighting', 'Lights & Lighting'), ('Consumer Electronics', 'Consumer Electronics'), ('Beauty & Health', 'Beauty & Health'), ('Shoes', 'Shoes'), ('Luggage & Bags', 'Luggage & Bags'), ('Electronic Components & Supplies', 'Electronic Components & Supplies'), ('Tools', 'Tools'), (' Mother & Kids', ' Mother & Kids'), ('Furniture', 'Furniture'), ('Jewelry & Accessories', 'Jewelry & Accessories'), ('Watches', 'Watches'), ('Hair Extensions and Wigs', 'Hair Extensions and Wigs'), ('Virtual Goods', 'Virtual Goods'), ('Novelty and Special Use', 'Novelty and Special Use'), ('Weddings and Events', 'Weddings and Events'), ('Women’s Clothing', 'Women’s Clothing'), ('Men’s Clothing', 'Men’s Clothing'), ('Apparel Accessories', 'Apparel Accessories'), ('Underwear and Sleepwears', 'Underwear and Sleepwears'), ('Cellphones & Telecommunications', 'Cellphones & Telecommunications')], default='United States', max_length=250, null=True),
        ),
    ]
