# Generated by Django 4.2 on 2023-07-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technology',
        ),
        migrations.RemoveField(
            model_name='country',
            name='country_number',
        ),
        migrations.AlterField(
            model_name='course',
            name='technology',
            field=models.CharField(blank=True, choices=[('shopify', 'Shopify'), ('wooCommerce', 'WooCommerce'), ('cart functionality', 'Cart Functionality'), ('magento', 'magento'), ('salesforce commerce cloud', 'Salesforce Commerce Cloud'), ('prestashop', 'PrestaShop'), ('vtex', 'VTEX'), ('bigcommerce', 'Bigcommerce'), ('ibm websphere commerce', 'IBM Websphere Commerce'), ('sap commerce cloud', 'SAP Commerce Cloud'), ('shopware', 'Shopware'), ('shoptet', 'Shoptet'), ('opencart', 'OpenCart'), ('nopcommerce', 'nopcommerce'), ('oracle commerce', 'Oracle Commerce'), ('intershop', 'Intershop'), ('hybris', 'Hybris'), ('zen cart', 'Zen Cart'), ('oracle commerce cloud', 'Oracle Commerce Cloud'), ('lightspeed ecom', 'Lightspeed eCom'), ('epages', 'EPages'), ('cloudcart', 'CloudCart'), ('kajabi', 'Kajabi'), ('loja integrada', 'Loja Integrada'), ('oxid eshop', 'OXID eShop'), ('riskified', 'Riskified'), ('x-cart', 'X-Cart'), ('commerce server', 'Commerce Server'), ('drupal commerce', 'Drupal Commerce'), ('oscommerce', 'osCommerce'), ('91app', '91App'), ('nuvemshop', 'Nuvemshop'), ('mycashflow', 'Mycashflow'), ('ticimax', 'Ticimax'), ('ecwid', 'Ecwid'), ('gambio', 'Gambio'), ('craft commerce', 'Craft Commerce'), ('ideasoft', 'Ideasoft'), ('ceres', 'Ceres'), ('t-soft', 'T-Soft'), ('storeden', 'Storeden'), ('vtex integrated store', 'VTEX Integrated Store'), ('ccv shop', 'CCV Shop'), ('big cartel', 'Big Cartel'), ('miva', 'Miva'), ('irroba', 'Irroba'), ('volusion', 'Volusion'), ('yepcomm', 'Yepcomm'), ('xtcommerce', 'xtCommerce'), ('ec-cube', 'EC-CUBE')], default='shopify', max_length=250, null=True),
        ),
    ]
