# Generated by Django 4.2 on 2023-09-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_course_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.CharField(blank=True, choices=[('Tools & Home Improvement', 'tools & home improvement'), ("Women's Fashion", "women's fashion"), ("Men's Fashion", "men's fashion"), ('Phones & Telecommunications', 'phones & telecommunications'), ('Computer, Office & Security', 'computer, office & security'), ('Consumer Electronics', 'consumer electronics'), ('Jewelry & Watches', 'jewelry & watches'), ('Home, Pet & Appliances', 'home, pet & appliances'), ('Bags & Shoes', 'bags & shoes'), ('Toys , Kids & Babies', 'toys , kids & babies'), ('Outdoor Fun & Sports', 'outdoor fun & sports'), ('Beauty, Health & Hair', 'beauty, health & hair'), ('Automobiles & Motorcycles', 'automobiles & motorcycles'), ('Home & Garden', 'home & garden'), ('Sports & Entertainment', 'sports & entertainment')], default='tools & home improvement', max_length=250, null=True),
        ),
    ]
