# Generated by Django 4.2 on 2023-07-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_course_button_alter_course_countries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
        migrations.AddField(
            model_name='course',
            name='site_type',
            field=models.IntegerField(choices=[(0, 'facebook'), (1, 'instagram'), (2, 'pinterest')], default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='shopify_price',
            field=models.DecimalField(decimal_places=2, default=3.56, help_text='Product price from shopify', max_digits=10),
            preserve_default=False,
        ),
    ]
