# Generated by Django 4.2 on 2023-07-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_course_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='featured',
        ),
    ]
