# Generated by Django 4.2 on 2023-09-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_otheraliexpresssupplierslinks_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliexpressordergrowth',
            name='order_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
