# Generated by Django 4.2 on 2023-07-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_course_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='facebook_comment',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Amount of comment generated', max_digits=10),
        ),
    ]
