# Generated by Django 4.2 on 2023-09-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_aliexpressordergrowth_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='links_to_ads',
        ),
        migrations.RemoveField(
            model_name='course',
            name='links_to_others_stores',
        ),
        migrations.RemoveField(
            model_name='course',
            name='links_to_others_suppliers',
        ),
        migrations.AddField(
            model_name='store',
            name='store_links',
            field=models.TextField(blank=True, help_text='link that will take to ads', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='shopify_links',
            field=models.TextField(blank=True, help_text='A link that will take to a single the store', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
