# Generated by Django 4.2 on 2023-07-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_course_facebook_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='name_of_product',
        ),
        migrations.AlterField(
            model_name='course',
            name='facebook_comment',
            field=models.IntegerField(default=0, help_text='Amount of comment generated'),
        ),
    ]
