# Generated by Django 4.2 on 2023-09-17 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_remove_course_links_to_ads_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='name_of_store',
        ),
        migrations.AddField(
            model_name='store',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.course'),
        ),
    ]
