# Generated by Django 4.2 on 2023-07-31 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_course_options_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='OtherAliexpressSuppliersLinks',
        ),
        migrations.RemoveField(
            model_name='course',
            name='otherShopifyLinks',
        ),
        migrations.AddField(
            model_name='othershopifylinks',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='content.course'),
            preserve_default=False,
        ),
    ]
