# Generated by Django 4.2 on 2023-09-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_remove_course_name_of_store_store_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='links_to_ads',
            field=models.TextField(blank=True, help_text='A link that will take to ads', null=True),
        ),
    ]
