# Generated by Django 4.2 on 2023-09-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_course_links_to_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='facebook_care',
            field=models.IntegerField(default=0, help_text='Amount of facebook care'),
        ),
        migrations.AlterField(
            model_name='course',
            name='button',
            field=models.CharField(blank=True, choices=[('buy now', 'Buy Now'), ('shop now', 'Shop Now'), ('learn more', 'Learn More'), ('Grab Yours', 'Grab Yours'), ('sign up', 'Sign Up'), ('send message', 'Send Message'), ('book now', 'Book Now'), ('install now', 'Install Now'), ('get directions', 'Get Directions'), ('watch more', 'Watch More'), ('view', 'View'), ('apply now', 'Apply Now'), ('like this page', 'Like This Page'), ('download', 'Download'), ('get offer', 'Get Offer'), ('get tickets', 'Get Tickets'), ('play game', 'Play Game'), ('try it', 'Try It'), ('contact us', 'Contact Us'), ('send whatsapp message', 'Send Whatsapp Message'), ('get quote', 'Get Quote'), ('call now', 'Call Now'), ('donate now', 'Donate Now'), ('buy tickets', 'Buy Tickets'), ('listen now', 'Listen Now'), ('subscribe', 'Subscribe'), ('get show times', 'Get Show Times'), ('view event', 'View Event'), ('see menu', 'See Menu'), ('read', 'Read'), ('use app', 'Use App'), ('order now', 'Order Now'), ('request time', 'Request Time'), ('join', 'Join'), ('open link', 'Open Link'), ('start order', 'Start Order'), ('install app', 'Install App'), ('get your code', 'Get Your Code'), ('see more', 'See More'), ('play now', 'Play Now'), ('see details', 'See Details'), ('open camera', 'Open Camera'), ('sell now', 'Sell Now'), ('buy', 'Buy'), ('about this website', 'About This Website'), ('messsage', 'Messsage'), ('follow', 'Follow'), ('try it', 'Try it'), ('like page', 'Like Page'), ('donate', 'Donate'), ('watch video', 'Watch Video'), ('visit website', 'Visit Website'), ('register now', 'Register Now'), ('email now', 'Email Now'), ('use offer', 'Use Offer'), ('add to profil', 'Add To Profil'), ('turn on', 'Turn On'), ('invite friends', 'Invite Friends'), ('see more', 'see more'), ('visit instagram profile', 'Visit Instagram Profile'), ('go live', 'go live'), ('add to cart', 'Add To Cart'), ('vote now', 'Vote Now'), ('intrested', 'Intrested'), ('see all events', 'See All Events'), ('save', 'Save'), ('search', 'Search'), ('remind me', 'Remind Me'), ('watch yours', 'Watch Yours'), ('save offer', 'Save Offer'), ('get deal', 'Get Deal'), ('get reminded', 'Get Reminded'), ('book test drive', 'Book Test Drive'), ('call', 'Call')], default='buy now', max_length=250, null=True),
        ),
    ]
