# Generated by Django 4.2 on 2023-07-31 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_remove_course_otheraliexpresssupplierslinks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otheraliexpresssupplierslinks',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='content.course'),
            preserve_default=False,
        ),
    ]
