# Generated by Django 4.2 on 2023-12-26 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_aliexpressordergrowth_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': '1. Products'},
        ),
        migrations.RenameField(
            model_name='city',
            old_name='course',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='course',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='otheraliexpresssupplierslinks',
            old_name='course',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='othershopifylinks',
            old_name='course',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='course',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='course',
            new_name='product',
        ),
    ]
