# Generated by Django 4.2 on 2023-08-03 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_course_ship_from'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '1. Courses'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name_plural': '1. Stores'},
        ),
        migrations.AddField(
            model_name='course',
            name='next_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='content.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='previous_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='content.course'),
        ),
    ]
