# Generated by Django 4.2 on 2023-08-03 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_course_options_alter_store_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='previous_post',
        ),
        migrations.AddField(
            model_name='course',
            name='first_related_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_related', to='content.course'),
        ),
    ]
