# Generated by Django 4.2 on 2023-12-31 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_rename_course_product_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='MainShopifyStore',
        ),
        migrations.AlterModelOptions(
            name='mainshopifystore',
            options={'verbose_name_plural': 'MainShopifyStore'},
        ),
    ]
