# Generated by Django 4.2 on 2023-08-03 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_remove_course_previous_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='next_post',
        ),
        migrations.AddField(
            model_name='course',
            name='second_related_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_related', to='content.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='third_related_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_related', to='content.course'),
        ),
    ]
