# Generated by Django 4.2 on 2023-12-31 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_rename_shopify_links_product_main_shopify_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_shopify_links',
        ),
    ]
