# Generated by Django 4.2 on 2024-01-02 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_remove_product_main_shopify_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='ads_started_running_on',
        ),
    ]
