# Generated by Django 4.2 on 2024-01-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_rename_created_at_product_ads_started_running_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='site_type',
            field=models.IntegerField(choices=[(0, 'facebook'), (1, 'tiktok'), (2, 'pinterest')], default=0),
        ),
    ]
