# Generated by Django 4.2 on 2024-01-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_alter_otheraliexpresssupplierslinks_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='site_type',
            field=models.IntegerField(choices=[('facebook', 'Facebook'), ('tiktok', 'Tiktok'), ('pinterest', 'Pinterest')], default='Facebook'),
        ),
    ]
