# Generated by Django 4.2 on 2024-01-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_alter_product_site_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='site_type',
            field=models.IntegerField(choices=[(0, 'facebook'), (1, 'tiktok'), (2, 'pinterest')], default=0),
        ),
    ]
